services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  rails:
    build: .
    tty: true
    stdin_open: true
    command: sh -c "./docker-scripts/rails.sh"
    # command: sh -c "rm -f tmp/pids/server.pid && bin/rails server -p 3000 -b 0.0.0.0"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  node_modules:
  # js_css:
  #   build: .
  #   container_name: js_css
  #   restart: unless-stopped
  #   tty: true
  #   command: sh -c "yarn build:css --watch && yarn build --watch"
  #   volumes:
  #     - .:/crm7
  #   depends_on:
  #     - db
  #     - rails
